name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create backend .env file
      run: echo "${{ secrets.BACKEND_ENV_FILE }}" > backend/.env

    - name: Check code format
      run: npm run format

    - name: Lint code
      run: npm run lint

    - name: Run backend tests
      run: npm run test:backend

    - name: Build frontend
      run: npm run build --workspace frontend

    - name: Validate commit messages
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: commitlint.config.js

    - name: Check PR for passing CI
      if: github.event_name == 'pull_request'
      run: echo "All CI checks passed."

    - name: Fail CI if tests not ok
      if: failure()
      run: |
        echo "Tests failed. Blocking merge."
        exit 1
