name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  ci:
    name: CI Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create backend .env file
      run: echo "${{ secrets.BACKEND_ENV_FILE }}" > backend/.env

    - name: Check code format
      run: npm run format

    - name: Lint code
      run: npm run lint

    - name: Run backend tests
      run: npm run test:backend

    - name: Build frontend
      run: npm run build --workspace frontend

    - name: Validate commit messages
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: commitlint.config.js

    - name: Check PR for passing CI
      if: github.event_name == 'pull_request'
      run: echo "All CI checks passed."

    - name: Fail CI if tests not ok
      if: failure()
      run: |
        echo "Tests failed. Blocking merge."
        exit 1

  cd:
    name: CD Workflow
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    container:
      image: ghcr.io/railwayapp/cli:latest
      env:
        SVC_ID: my-service-id
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build --workspace frontend

    - name: Deploy to Railway
      run: railway up --service=${{ env.SVC_ID }}
